In [1]:
import os
import json

import pandas as pd
from pyBiodatafuse.annotators.pubchem import get_protein_molecule_screened

In [2]:
bridgedb_dataframe = pd.DataFrame(
    {
        "identifier": ["EGFR", "EGFR", "EGFR", "HTR3A", "HTR3A"],
        "identifier.source": ["HGNC", "HGNC", "HGNC", "HGNC", "HGNC"],
        "target": ["C9JYS6", "P00533", "Q504U8", "A0A0B4J205", "P46098"],
        "target.source": [
            "Uniprot-TrEMBL",
            "Uniprot-TrEMBL",
            "Uniprot-TrEMBL",
            "Uniprot-TrEMBL",
            "Uniprot-TrEMBL",
        ],
    }
)
bridgedb_dataframe.head()

  identifier identifier.source      target   target.source
0       EGFR              HGNC      C9JYS6  Uniprot-TrEMBL
1       EGFR              HGNC      P00533  Uniprot-TrEMBL
2       EGFR              HGNC      Q504U8  Uniprot-TrEMBL
3      HTR3A              HGNC  A0A0B4J205  Uniprot-TrEMBL
4      HTR3A              HGNC      P46098  Uniprot-TrEMBL

In [3]:
obtained_data, metadata = get_protein_molecule_screened(bridgedb_dataframe)
obtained_data

,identifier,identifier.source,target,target.source,PubChem_assays
0,EGFR,HGNC,P00533,Uniprot-TrEMBL,"[{'pubchem_assay_id': '1727', 'assay_type': 'A..."
1,HTR3A,HGNC,A0A0B4J205,Uniprot-TrEMBL,"[{'pubchem_assay_id': nan, 'assay_type': nan, ..."